version: '3'
services:

  #APP
  app:
    build:
      context: .
      dockerfile: ./easydock/Dockerfile
      args:
        - PHP_V=${PHP_V}
    container_name: ${APP_SID}-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ${APP_SRC}:/var/www/:cached
      - ./easydock/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./easydock/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  #NGINX
  nginx:
    image: nginx:alpine
    container_name: ${APP_SID}-nginx
    restart: always
    tty: true
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_SRC}:/var/www/
      - ./easydock/nginx/conf.d/:/etc/nginx/conf.d/

  #MYSQL
  mysql:
    image: mysql:${DB_VERS}
    container_name: ${APP_SID}-mysql
    restart: always
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./easydock/mysql/data:/var/lib/mysql/

  #REDIS
  redis:
    image: redis:latest
    container_name: ${APP_SID}-redis
    restart: always
    expose:
      - 6379
    ports:
      - ${RDS_PORT}:6379

  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_SID}-pma
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${PMA_PORT}:80

  #MAILHOG
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_SID}-mailhog
    restart: always
    expose:
      - 1025
    ports:
      - ${MH_PORT}:8025